project:
  type: website
  output-dir: docs

website:
  title: "Matic Jančič: Teaching portfolio"
  navbar:
    right:
      - about.qmd
      - publications.qmd
      - icon: github
        href: https://github.com/maticjancic
      - icon: linkedin
        href: https://www.linkedin.com/in/maticjancic/
      - text: "{{< ai researchgate >}}"
        href: https://www.researchgate.net/profile/Matic-Jancic
      - text: "{{< ai orcid >}}"
        href: https://orcid.org/0000-0002-6872-4078
      - text: "{{< iconify mdi email-edit-outline size=1.8 >}}"
        href: mailto:matic.jancic@famnit.upr.si


  search: 
    location: navbar
    type: overlay
format:
  html:
    theme: Flatly
    css: styles.css

editor: source

